<?php

namespace BlogBundle\Repository;

/**
 * PostTranlationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTranlationRepository extends \Doctrine\ORM\EntityRepository
{
}
